firewall-cmd --zone=public --add-port=10000/tcp --permanent
firewall-cmd --zone=public --add-port=10001/tcp --permanent
firewall-cmd --zone=public --add-port=10002/tcp --permanent
firewall-cmd --zone=public --add-port=10003/tcp --permanent
firewall-cmd --zone=public --add-port=10004/tcp --permanent
firewall-cmd --zone=public --add-port=10005/tcp --permanent
firewall-cmd --zone=public --add-port=10006/tcp --permanent
firewall-cmd --zone=public --add-port=10007/tcp --permanent
firewall-cmd --zone=public --add-port=10008/tcp --permanent
firewall-cmd --zone=public --add-port=10009/tcp --permanent
firewall-cmd --zone=public --add-port=10010/tcp --permanent
firewall-cmd --zone=public --add-port=10011/tcp --permanent
firewall-cmd --zone=public --add-port=10012/tcp --permanent
firewall-cmd --zone=public --add-port=10013/tcp --permanent
firewall-cmd --zone=public --add-port=10014/tcp --permanent
firewall-cmd --zone=public --add-port=10015/tcp --permanent
firewall-cmd --zone=public --add-port=10016/tcp --permanent
firewall-cmd --zone=public --add-port=10017/tcp --permanent
firewall-cmd --zone=public --add-port=10018/tcp --permanent
firewall-cmd --zone=public --add-port=10019/tcp --permanent
firewall-cmd --zone=public --add-port=10020/tcp --permanent
firewall-cmd --zone=public --add-port=10021/tcp --permanent
firewall-cmd --zone=public --add-port=10022/tcp --permanent
firewall-cmd --zone=public --add-port=10023/tcp --permanent
firewall-cmd --zone=public --add-port=10024/tcp --permanent
firewall-cmd --zone=public --add-port=10025/tcp --permanent
firewall-cmd --zone=public --add-port=10026/tcp --permanent
firewall-cmd --zone=public --add-port=10027/tcp --permanent
firewall-cmd --zone=public --add-port=10028/tcp --permanent
firewall-cmd --zone=public --add-port=10029/tcp --permanent
firewall-cmd --zone=public --add-port=10030/tcp --permanent
firewall-cmd --zone=public --add-port=10031/tcp --permanent
firewall-cmd --zone=public --add-port=10032/tcp --permanent
firewall-cmd --zone=public --add-port=10033/tcp --permanent
firewall-cmd --zone=public --add-port=10034/tcp --permanent
firewall-cmd --zone=public --add-port=10035/tcp --permanent
firewall-cmd --zone=public --add-port=10036/tcp --permanent
firewall-cmd --zone=public --add-port=10037/tcp --permanent
firewall-cmd --zone=public --add-port=10038/tcp --permanent
firewall-cmd --zone=public --add-port=10039/tcp --permanent
firewall-cmd --zone=public --add-port=10040/tcp --permanent
firewall-cmd --zone=public --add-port=10041/tcp --permanent
firewall-cmd --zone=public --add-port=10042/tcp --permanent
firewall-cmd --zone=public --add-port=10043/tcp --permanent
firewall-cmd --zone=public --add-port=10044/tcp --permanent
firewall-cmd --zone=public --add-port=10045/tcp --permanent
firewall-cmd --zone=public --add-port=10046/tcp --permanent
firewall-cmd --zone=public --add-port=10047/tcp --permanent
firewall-cmd --zone=public --add-port=10048/tcp --permanent
firewall-cmd --zone=public --add-port=10049/tcp --permanent
firewall-cmd --reload
