firewall-cmd --zone=public --add-port=10000/tcp --permanent
firewall-cmd --zone=public --add-port=10001/tcp --permanent
firewall-cmd --zone=public --add-port=10002/tcp --permanent
firewall-cmd --zone=public --add-port=10003/tcp --permanent
firewall-cmd --zone=public --add-port=10004/tcp --permanent
firewall-cmd --zone=public --add-port=10005/tcp --permanent
firewall-cmd --zone=public --add-port=10006/tcp --permanent
firewall-cmd --zone=public --add-port=10007/tcp --permanent
firewall-cmd --zone=public --add-port=10008/tcp --permanent
firewall-cmd --zone=public --add-port=10009/tcp --permanent
firewall-cmd --zone=public --add-port=10010/tcp --permanent
firewall-cmd --zone=public --add-port=10011/tcp --permanent
firewall-cmd --zone=public --add-port=10012/tcp --permanent
firewall-cmd --zone=public --add-port=10013/tcp --permanent
firewall-cmd --zone=public --add-port=10014/tcp --permanent
firewall-cmd --zone=public --add-port=10015/tcp --permanent
firewall-cmd --zone=public --add-port=10016/tcp --permanent
firewall-cmd --zone=public --add-port=10017/tcp --permanent
firewall-cmd --zone=public --add-port=10018/tcp --permanent
firewall-cmd --zone=public --add-port=10019/tcp --permanent
firewall-cmd --zone=public --add-port=10020/tcp --permanent
firewall-cmd --zone=public --add-port=10021/tcp --permanent
firewall-cmd --zone=public --add-port=10022/tcp --permanent
firewall-cmd --zone=public --add-port=10023/tcp --permanent
firewall-cmd --zone=public --add-port=10024/tcp --permanent
firewall-cmd --zone=public --add-port=10025/tcp --permanent
firewall-cmd --zone=public --add-port=10026/tcp --permanent
firewall-cmd --zone=public --add-port=10027/tcp --permanent
firewall-cmd --zone=public --add-port=10028/tcp --permanent
firewall-cmd --zone=public --add-port=10029/tcp --permanent
firewall-cmd --zone=public --add-port=10030/tcp --permanent
firewall-cmd --zone=public --add-port=10031/tcp --permanent
firewall-cmd --zone=public --add-port=10032/tcp --permanent
firewall-cmd --zone=public --add-port=10033/tcp --permanent
firewall-cmd --zone=public --add-port=10034/tcp --permanent
firewall-cmd --zone=public --add-port=10035/tcp --permanent
firewall-cmd --zone=public --add-port=10036/tcp --permanent
firewall-cmd --zone=public --add-port=10037/tcp --permanent
firewall-cmd --zone=public --add-port=10038/tcp --permanent
firewall-cmd --zone=public --add-port=10039/tcp --permanent
firewall-cmd --zone=public --add-port=10040/tcp --permanent
firewall-cmd --zone=public --add-port=10041/tcp --permanent
firewall-cmd --zone=public --add-port=10042/tcp --permanent
firewall-cmd --zone=public --add-port=10043/tcp --permanent
firewall-cmd --zone=public --add-port=10044/tcp --permanent
firewall-cmd --zone=public --add-port=10045/tcp --permanent
firewall-cmd --zone=public --add-port=10046/tcp --permanent
firewall-cmd --zone=public --add-port=10047/tcp --permanent
firewall-cmd --zone=public --add-port=10048/tcp --permanent
firewall-cmd --zone=public --add-port=10049/tcp --permanent
firewall-cmd --zone=public --add-port=10050/tcp --permanent
firewall-cmd --zone=public --add-port=10051/tcp --permanent
firewall-cmd --zone=public --add-port=10052/tcp --permanent
firewall-cmd --zone=public --add-port=10053/tcp --permanent
firewall-cmd --zone=public --add-port=10054/tcp --permanent
firewall-cmd --zone=public --add-port=10055/tcp --permanent
firewall-cmd --zone=public --add-port=10056/tcp --permanent
firewall-cmd --zone=public --add-port=10057/tcp --permanent
firewall-cmd --zone=public --add-port=10058/tcp --permanent
firewall-cmd --zone=public --add-port=10059/tcp --permanent
firewall-cmd --zone=public --add-port=10060/tcp --permanent
firewall-cmd --zone=public --add-port=10061/tcp --permanent
firewall-cmd --zone=public --add-port=10062/tcp --permanent
firewall-cmd --zone=public --add-port=10063/tcp --permanent
firewall-cmd --zone=public --add-port=10064/tcp --permanent
firewall-cmd --zone=public --add-port=10065/tcp --permanent
firewall-cmd --zone=public --add-port=10066/tcp --permanent
firewall-cmd --zone=public --add-port=10067/tcp --permanent
firewall-cmd --zone=public --add-port=10068/tcp --permanent
firewall-cmd --zone=public --add-port=10069/tcp --permanent
firewall-cmd --zone=public --add-port=10070/tcp --permanent
firewall-cmd --zone=public --add-port=10071/tcp --permanent
firewall-cmd --zone=public --add-port=10072/tcp --permanent
firewall-cmd --zone=public --add-port=10073/tcp --permanent
firewall-cmd --zone=public --add-port=10074/tcp --permanent
firewall-cmd --zone=public --add-port=10075/tcp --permanent
firewall-cmd --zone=public --add-port=10076/tcp --permanent
firewall-cmd --zone=public --add-port=10077/tcp --permanent
firewall-cmd --zone=public --add-port=10078/tcp --permanent
firewall-cmd --zone=public --add-port=10079/tcp --permanent
firewall-cmd --zone=public --add-port=10080/tcp --permanent
firewall-cmd --zone=public --add-port=10081/tcp --permanent
firewall-cmd --zone=public --add-port=10082/tcp --permanent
firewall-cmd --zone=public --add-port=10083/tcp --permanent
firewall-cmd --zone=public --add-port=10084/tcp --permanent
firewall-cmd --zone=public --add-port=10085/tcp --permanent
firewall-cmd --zone=public --add-port=10086/tcp --permanent
firewall-cmd --zone=public --add-port=10087/tcp --permanent
firewall-cmd --zone=public --add-port=10088/tcp --permanent
firewall-cmd --zone=public --add-port=10089/tcp --permanent
firewall-cmd --zone=public --add-port=10090/tcp --permanent
firewall-cmd --zone=public --add-port=10091/tcp --permanent
firewall-cmd --zone=public --add-port=10092/tcp --permanent
firewall-cmd --zone=public --add-port=10093/tcp --permanent
firewall-cmd --zone=public --add-port=10094/tcp --permanent
firewall-cmd --zone=public --add-port=10095/tcp --permanent
firewall-cmd --zone=public --add-port=10096/tcp --permanent
firewall-cmd --zone=public --add-port=10097/tcp --permanent
firewall-cmd --zone=public --add-port=10098/tcp --permanent
firewall-cmd --zone=public --add-port=10099/tcp --permanent
firewall-cmd --zone=public --add-port=10100/tcp --permanent
firewall-cmd --zone=public --add-port=10101/tcp --permanent
firewall-cmd --zone=public --add-port=10102/tcp --permanent
firewall-cmd --zone=public --add-port=10103/tcp --permanent
firewall-cmd --zone=public --add-port=10104/tcp --permanent
firewall-cmd --zone=public --add-port=10105/tcp --permanent
firewall-cmd --zone=public --add-port=10106/tcp --permanent
firewall-cmd --zone=public --add-port=10107/tcp --permanent
firewall-cmd --zone=public --add-port=10108/tcp --permanent
firewall-cmd --zone=public --add-port=10109/tcp --permanent
firewall-cmd --zone=public --add-port=10110/tcp --permanent
firewall-cmd --zone=public --add-port=10111/tcp --permanent
firewall-cmd --zone=public --add-port=10112/tcp --permanent
firewall-cmd --zone=public --add-port=10113/tcp --permanent
firewall-cmd --zone=public --add-port=10114/tcp --permanent
firewall-cmd --zone=public --add-port=10115/tcp --permanent
firewall-cmd --zone=public --add-port=10116/tcp --permanent
firewall-cmd --zone=public --add-port=10117/tcp --permanent
firewall-cmd --zone=public --add-port=10118/tcp --permanent
firewall-cmd --zone=public --add-port=10119/tcp --permanent
firewall-cmd --zone=public --add-port=10120/tcp --permanent
firewall-cmd --zone=public --add-port=10121/tcp --permanent
firewall-cmd --zone=public --add-port=10122/tcp --permanent
firewall-cmd --zone=public --add-port=10123/tcp --permanent
firewall-cmd --zone=public --add-port=10124/tcp --permanent
firewall-cmd --zone=public --add-port=10125/tcp --permanent
