firewall-cmd --zone=public --add-port=20000/tcp --permanent
firewall-cmd --zone=public --add-port=20001/tcp --permanent
firewall-cmd --zone=public --add-port=20002/tcp --permanent
firewall-cmd --zone=public --add-port=20003/tcp --permanent
firewall-cmd --zone=public --add-port=20004/tcp --permanent
firewall-cmd --zone=public --add-port=20005/tcp --permanent
firewall-cmd --zone=public --add-port=20006/tcp --permanent
firewall-cmd --zone=public --add-port=20007/tcp --permanent
firewall-cmd --zone=public --add-port=20008/tcp --permanent
firewall-cmd --zone=public --add-port=20009/tcp --permanent
firewall-cmd --zone=public --add-port=20010/tcp --permanent
firewall-cmd --zone=public --add-port=20011/tcp --permanent
firewall-cmd --zone=public --add-port=20012/tcp --permanent
firewall-cmd --zone=public --add-port=20013/tcp --permanent
firewall-cmd --zone=public --add-port=20014/tcp --permanent
firewall-cmd --zone=public --add-port=20015/tcp --permanent
firewall-cmd --zone=public --add-port=20016/tcp --permanent
firewall-cmd --zone=public --add-port=20017/tcp --permanent
firewall-cmd --zone=public --add-port=20018/tcp --permanent
firewall-cmd --zone=public --add-port=20019/tcp --permanent
firewall-cmd --zone=public --add-port=20020/tcp --permanent
firewall-cmd --zone=public --add-port=20021/tcp --permanent
firewall-cmd --zone=public --add-port=20022/tcp --permanent
firewall-cmd --zone=public --add-port=20023/tcp --permanent
firewall-cmd --zone=public --add-port=20024/tcp --permanent
firewall-cmd --zone=public --add-port=20025/tcp --permanent
firewall-cmd --zone=public --add-port=20026/tcp --permanent
firewall-cmd --zone=public --add-port=20027/tcp --permanent
firewall-cmd --zone=public --add-port=20028/tcp --permanent
firewall-cmd --zone=public --add-port=20029/tcp --permanent
firewall-cmd --zone=public --add-port=20030/tcp --permanent
firewall-cmd --zone=public --add-port=20031/tcp --permanent
firewall-cmd --zone=public --add-port=20032/tcp --permanent
firewall-cmd --zone=public --add-port=20033/tcp --permanent
firewall-cmd --zone=public --add-port=20034/tcp --permanent
firewall-cmd --zone=public --add-port=20035/tcp --permanent
firewall-cmd --zone=public --add-port=20036/tcp --permanent
firewall-cmd --zone=public --add-port=20037/tcp --permanent
firewall-cmd --zone=public --add-port=20038/tcp --permanent
firewall-cmd --zone=public --add-port=20039/tcp --permanent
firewall-cmd --zone=public --add-port=20040/tcp --permanent
firewall-cmd --zone=public --add-port=20041/tcp --permanent
firewall-cmd --zone=public --add-port=20042/tcp --permanent
firewall-cmd --zone=public --add-port=20043/tcp --permanent
firewall-cmd --zone=public --add-port=20044/tcp --permanent
firewall-cmd --zone=public --add-port=20045/tcp --permanent
firewall-cmd --zone=public --add-port=20046/tcp --permanent
firewall-cmd --zone=public --add-port=20047/tcp --permanent
firewall-cmd --zone=public --add-port=20048/tcp --permanent
firewall-cmd --zone=public --add-port=20049/tcp --permanent
firewall-cmd --zone=public --add-port=20050/tcp --permanent
firewall-cmd --zone=public --add-port=20051/tcp --permanent
firewall-cmd --zone=public --add-port=20052/tcp --permanent
firewall-cmd --zone=public --add-port=20053/tcp --permanent
firewall-cmd --zone=public --add-port=20054/tcp --permanent
firewall-cmd --zone=public --add-port=20055/tcp --permanent
firewall-cmd --zone=public --add-port=20056/tcp --permanent
firewall-cmd --zone=public --add-port=20057/tcp --permanent
firewall-cmd --zone=public --add-port=20058/tcp --permanent
firewall-cmd --zone=public --add-port=20059/tcp --permanent
firewall-cmd --zone=public --add-port=20060/tcp --permanent
firewall-cmd --zone=public --add-port=20061/tcp --permanent
firewall-cmd --zone=public --add-port=20062/tcp --permanent
firewall-cmd --zone=public --add-port=20063/tcp --permanent
firewall-cmd --zone=public --add-port=20064/tcp --permanent
firewall-cmd --zone=public --add-port=20065/tcp --permanent
firewall-cmd --zone=public --add-port=20066/tcp --permanent
firewall-cmd --zone=public --add-port=20067/tcp --permanent
firewall-cmd --zone=public --add-port=20068/tcp --permanent
firewall-cmd --zone=public --add-port=20069/tcp --permanent
firewall-cmd --zone=public --add-port=20070/tcp --permanent
firewall-cmd --zone=public --add-port=20071/tcp --permanent
firewall-cmd --zone=public --add-port=20072/tcp --permanent
firewall-cmd --zone=public --add-port=20073/tcp --permanent
firewall-cmd --zone=public --add-port=20074/tcp --permanent
firewall-cmd --zone=public --add-port=20075/tcp --permanent
firewall-cmd --zone=public --add-port=20076/tcp --permanent
firewall-cmd --zone=public --add-port=20077/tcp --permanent
firewall-cmd --zone=public --add-port=20078/tcp --permanent
firewall-cmd --zone=public --add-port=20079/tcp --permanent
firewall-cmd --zone=public --add-port=20080/tcp --permanent
firewall-cmd --zone=public --add-port=20081/tcp --permanent
firewall-cmd --zone=public --add-port=20082/tcp --permanent
firewall-cmd --zone=public --add-port=20083/tcp --permanent
firewall-cmd --zone=public --add-port=20084/tcp --permanent
firewall-cmd --zone=public --add-port=20085/tcp --permanent
firewall-cmd --zone=public --add-port=20086/tcp --permanent
firewall-cmd --zone=public --add-port=20087/tcp --permanent
firewall-cmd --zone=public --add-port=20088/tcp --permanent
firewall-cmd --zone=public --add-port=20089/tcp --permanent
firewall-cmd --zone=public --add-port=20090/tcp --permanent
firewall-cmd --zone=public --add-port=20091/tcp --permanent
firewall-cmd --zone=public --add-port=20092/tcp --permanent
firewall-cmd --zone=public --add-port=20093/tcp --permanent
firewall-cmd --zone=public --add-port=20094/tcp --permanent
firewall-cmd --zone=public --add-port=20095/tcp --permanent
firewall-cmd --zone=public --add-port=20096/tcp --permanent
firewall-cmd --zone=public --add-port=20097/tcp --permanent
firewall-cmd --zone=public --add-port=20098/tcp --permanent
firewall-cmd --zone=public --add-port=20099/tcp --permanent
firewall-cmd --zone=public --add-port=20100/tcp --permanent
firewall-cmd --zone=public --add-port=20101/tcp --permanent
firewall-cmd --zone=public --add-port=20102/tcp --permanent
firewall-cmd --zone=public --add-port=20103/tcp --permanent
firewall-cmd --zone=public --add-port=20104/tcp --permanent
firewall-cmd --zone=public --add-port=20105/tcp --permanent
firewall-cmd --zone=public --add-port=20106/tcp --permanent
firewall-cmd --zone=public --add-port=20107/tcp --permanent
firewall-cmd --zone=public --add-port=20108/tcp --permanent
firewall-cmd --zone=public --add-port=20109/tcp --permanent
firewall-cmd --zone=public --add-port=20110/tcp --permanent
firewall-cmd --zone=public --add-port=20111/tcp --permanent
firewall-cmd --zone=public --add-port=20112/tcp --permanent
firewall-cmd --zone=public --add-port=20113/tcp --permanent
firewall-cmd --zone=public --add-port=20114/tcp --permanent
firewall-cmd --zone=public --add-port=20115/tcp --permanent
firewall-cmd --zone=public --add-port=20116/tcp --permanent
firewall-cmd --zone=public --add-port=20117/tcp --permanent
firewall-cmd --zone=public --add-port=20118/tcp --permanent
firewall-cmd --zone=public --add-port=20119/tcp --permanent
firewall-cmd --zone=public --add-port=20120/tcp --permanent
firewall-cmd --zone=public --add-port=20121/tcp --permanent
firewall-cmd --zone=public --add-port=20122/tcp --permanent
firewall-cmd --zone=public --add-port=20123/tcp --permanent
firewall-cmd --zone=public --add-port=20124/tcp --permanent
firewall-cmd --zone=public --add-port=20125/tcp --permanent
