firewall-cmd --zone=public --add-port=10000/tcp --permanent
firewall-cmd --zone=public --add-port=10001/tcp --permanent
firewall-cmd --zone=public --add-port=10002/tcp --permanent
firewall-cmd --zone=public --add-port=10003/tcp --permanent
firewall-cmd --zone=public --add-port=10004/tcp --permanent
firewall-cmd --zone=public --add-port=10005/tcp --permanent
firewall-cmd --zone=public --add-port=10006/tcp --permanent
firewall-cmd --zone=public --add-port=10007/tcp --permanent
firewall-cmd --zone=public --add-port=10008/tcp --permanent
firewall-cmd --zone=public --add-port=10009/tcp --permanent
firewall-cmd --zone=public --add-port=10010/tcp --permanent
firewall-cmd --zone=public --add-port=10011/tcp --permanent
firewall-cmd --zone=public --add-port=10012/tcp --permanent
firewall-cmd --zone=public --add-port=10013/tcp --permanent
firewall-cmd --zone=public --add-port=10014/tcp --permanent
firewall-cmd --zone=public --add-port=10015/tcp --permanent
firewall-cmd --zone=public --add-port=10016/tcp --permanent
firewall-cmd --zone=public --add-port=10017/tcp --permanent
firewall-cmd --zone=public --add-port=10018/tcp --permanent
firewall-cmd --zone=public --add-port=10019/tcp --permanent
firewall-cmd --reload
